version: '3.8'

services:
  easyssh:
    image: shanheee/easyssh:latest
    container_name: easyssh
    restart: unless-stopped
    ports:
      - "8520:8520"
    env_file:
      - ../.env
    depends_on:
      - postgres
      - redis
    networks:
      - easyssh-network

  postgres:
    image: postgres:16
    container_name: Easyssh_postgres
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - easyssh-network

  redis:
    image: redis:7
    container_name: Easyssh_redis
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
    networks:
      - easyssh-network

networks:
  easyssh-network:
    name: easyssh-network
    driver: bridge
