version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: Easyssh
    restart: always
    environment:
      POSTGRES_USER: easyssh
      POSTGRES_PASSWORD: easyssh_dev_password
      POSTGRES_DB: Easyssh_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: Easyssh_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
    command: redis-server --appendonly yes
